### ISSUE TITLE
socket.error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by HideakiAtsuyo** [barneygale/MCRcon#18]
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    main()
  File "demo.py", line 25, in main
    sock.connect((args.host, args.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused

**Comment by barneygale** [comment]
This is a network-level issue and nothing to do with this project. Ensure you have rcon enabled in server.properties and that the rcon port is not hidden by NAT or a firewall

**Comment by MadMartian** [comment]
It seems Minecraft Vanilla RCon needs to be patched due to a rather overt bug.  Upon investigation of the Minecraft source code (1.7.10 anyway) I discovered it disconnects the client immediately after the first command (which would be logging in) due to a misunderstanding of how the "finally" block in Java works.  In my case I abandoned RCon and opted for a modified version of _dtach_ (similar to _screen_), this is not ideal though.
